config/routes.rb
Rails.application.routes.draw do
 
  resources :pairings
  resources :profiles
  resources :subjects
  resources :schedules
  match '/auth/:provider/callback', :to => 'sessions#create', :via => [:get, :post]
  match 'auth/failure', :to => 'sessions#failure', :via => [:get, :post]
  match 'sessions/destroy', :as => 'logout', :via => [:get, :post]
  get 'sessions/start_test'
  get 'sessions/clear'
  get 'session/debug'

  get 'welcome/landing', :as => :welcome_landing
  get 'about/index'

  resources :users, only: [:destroy] do
    resources :profiles, only: [:show, :edit, :update, :destroy]
  end

  root 'welcome#landing'
  
  get 'schedules/index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  def create
    @profile = Profile.new(profile_params)

    if @profile.save
      redirect_to @profile, notice: 'Profile was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /profiles/1
  def update
    if @profile.update(profile_params)
      redirect_to @profile, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /profiles/1
  def destroy
    @profile.destroy
    redirect_to profiles_url, notice: 'Profile was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def profile_params
      params.require(:profile).permit(:primary_language, :secondary_language, :favorite_movie, :worst_movie, :favorite_genre, :user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.haml
= form_for @profile do |f|
  - if @profile.errors.any?
    #error_explanation
      %h2= "#{pluralize(@profile.errors.count, "error")} prohibited this profile from being saved:"
      %ul
        - @profile.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :primary_language
    = f.text_field :primary_language
  .field
    = f.label :secondary_language
    = f.text_field :secondary_language
  .field
    = f.label :favorite_movie
    = f.text_field :favorite_movie
  .field
    = f.label :worst_movie
    = f.text_field :worst_movie
  .field
    = f.label :favorite_genre
    = f.text_field :favorite_genre
  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Save'

app/views/profiles/edit.html.haml
%h1 Editing profile

app/views/profiles/index.html.haml
%h1 Listing profiles

%table
  %thead
    %tr
      %th Primary language
      %th Secondary language
      %th Favorite movie
      %th Worst movie
      %th Favorite genre
      %th User
      %th
      %th
      %th

  %tbody
    - @profiles.each do |profile|
      %tr
        %td= profile.primary_language
        %td= profile.secondary_language
        %td= profile.favorite_movie
        %td= profile.worst_movie
        %td= profile.favorite_genre
        %td= profile.user
        %td= link_to 'Show', profile
        %td= link_to 'Edit', edit_profile_path(profile)
        %td= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Profile', new_profile_path

app/views/profiles/new.html.haml
%h1 New profile

= render 'form'

= link_to 'Back', profiles_path

app/views/profiles/old_edit.html.haml
%h1 Editing profile

= render 'form'

= link_to 'Show', @profile
\|
= link_to 'Back', profiles_path

app/views/profiles/show.html.haml
%p#notice= notice

%p
  %b Primary language:
  = @profile.primary_language
%p
  %b Secondary language:
  = @profile.secondary_language
%p
  %b Favorite movie:
  = @profile.favorite_movie
%p
  %b Worst movie:
  = @profile.worst_movie
%p
  %b Favorite genre:
  = @profile.favorite_genre
%p
  %b User:
  = @profile.user

= link_to 'Edit', edit_profile_path(@profile)
\|
= link_to 'Back', profiles_path