config/routes.rb
Rails.application.routes.draw do
 
  resources :pairings
  resources :profiles
  resources :subjects
  resources :schedules
  match '/auth/:provider/callback', :to => 'sessions#create', :via => [:get, :post]
  match 'auth/failure', :to => 'sessions#failure', :via => [:get, :post]
  match 'sessions/destroy', :as => 'logout', :via => [:get, :post]
  get 'sessions/start_test'
  get 'sessions/clear'
  get 'session/debug'

  get 'welcome/landing', :as => :welcome_landing
  get 'about/index'

  resources :users, only: [:destroy] do
    resources :profiles, only: [:show, :edit, :update, :destroy]
  end

  root 'welcome#landing'
  
  get 'schedules/index'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  
  def index
    @schedules = Schedule.all 
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    #  id = params[:id] # retrieve movie ID from URI route
    @schedule = set_schedule  #Schedule.find(id)
  end

  # GET /movies/new
  def new
    @schedule = Schedule.new
  end

  # GET /movies/1/edit
  def edit
    @schedule = set_schedule
  end

  def create
    @schedule = Schedule.create!(schedule_params)
    flash[:notice] = "Appointment for #{@schedule.subject} was successfully created."
    redirect_to schedules_path
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    @schedule = set_schedule
    @schedule.update_attributes!(schedule_params)
    flash[:notice] = "Appointment for #{@schedule.subject} was successfully updated."
    redirect_to schedule_path(@schedule)
  end

  # DELETE /movies/1
  def destroy
    @schedule = set_schedule
    @schedule.destroy
    flash[:notice] = "Appointment for '#{@schedule.subject}' deleted."
    redirect_to schedules_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:tutor, :subject, :student, :timeslot)
    end
  
end

app/views/schedules/edit.html.haml
%h2 Edit Existing Appointment
= form_tag schedule_path(@schedule), :method => :put do
  = label :schedule, :timeslot, 'Time slot', :class => 'col-form-label'
  = text_field :schedule, :timeslot, :class => 'form-control'
  %br/
  = submit_tag 'Update Schedule Info', :class => 'btn btn-primary'
  = link_to 'Cancel', schedules_path, :class => 'btn btn-secondary'

app/views/schedules/index.html.haml
/ This file is app/views/movies/index.html.erb
%h2 All Schedules

= link_to 'Add a session', new_schedule_path

%table#movies.table.table-striped.col-md-12
  %thead
    %tr
      %th Available Tutors
  %tbody
    - @schedules.each do |schedule|
      %tr
        %td
          = schedule.subject
        %td
          = link_to 'Show', schedule
        %td
          = link_to 'Edit', edit_schedule_path(schedule)
        %td
          = link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' }

app/views/schedules/new.html.haml
%h2 Create New Appointment
= form_tag schedules_path do
  = label :schedule, :tutor, 'Tutor', :class => 'col-form-label'
  = text_field :schedule, :tutor, :class => 'form-control'
  = label :schedule, :subject, 'Subject', :class => 'col-form-label'
  = text_field :schedule, :subject, :class => 'form-control'
  = label :schedule, :timeslot, 'Time slot', :class => 'col-form-label'
  = text_field :schedule, :timeslot, :class => 'form-control'
  
  %br
  = submit_tag 'Save Changes', :class => 'btn btn-primary'
  = link_to 'Cancel', schedules_path, :class => 'btn btn-secondary'

app/views/schedules/show.html.haml
%h3 Details about your appointment

%ul#details
  %li
    Subject:
    = @schedule.subject
  %li
    Tutor:
    = @schedule.tutor
  %li 
    Time slot:
    = @schedule.timeslot

= link_to 'Edit', edit_schedule_path(@schedule)
= button_to 'Delete', schedule_path(@schedule), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-primary'
= link_to 'Back to Schedule list', schedules_path