config/routes.rb
Rails.application.routes.draw do
 
  resources :pairings
  resources :profiles
  resources :subjects
  resources :schedules
  match '/auth/:provider/callback', :to => 'sessions#create', :via => [:get, :post]
  match 'auth/failure', :to => 'sessions#failure', :via => [:get, :post]
  match 'sessions/destroy', :as => 'logout', :via => [:get, :post]
  get 'sessions/start_test'
  get 'sessions/clear'
  get 'session/debug'

  get 'welcome/landing', :as => :welcome_landing
  get 'about/index'

  resources :users, only: [:destroy] do
    resources :profiles, only: [:show, :edit, :update, :destroy]
  end

  root 'welcome#landing'
  
  get 'schedules/index'

end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
   
  
  def index
    @subjects = Subject.all 
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    #  id = params[:id] # retrieve movie ID from URI route
    @subject = set_subject  #Subject.find(id)
  end

  # GET /movies/new
  def new
    @subject = Subject.new
  end

  # GET /movies/1/edit
  def edit
    @subject = set_subject
  end

  def create
    @subject = Subject.create!(subject_params)
    flash[:notice] = "#{@subject.title} was successfully created."
    redirect_to subjects_path
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    @subject = set_subject
    @subject.update_attributes!(subject_params)
    flash[:notice] = "#{@subject.title} was successfully updated."
    redirect_to subject_path(@subject)
  end

  # DELETE /movies/1
  def destroy
    @subject = set_subject
    @subject.destroy
    flash[:notice] = "Subject '#{@subject.title}' deleted."
    redirect_to subjects_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:subjectcode, :title, :description, :create_date)
    end
end

app/views/subjects/edit.html.haml
%h2 Edit Existing Subject
= form_tag subject_path(@subject), :method => :put do
  = label :subject, :title, 'Title', :class => 'col-form-label'
  = text_field :subject, 'title', :class => 'form-control'
  %br/
  = submit_tag 'Update Subject Info', :class => 'btn btn-primary'
  = link_to 'Cancel', subjects_path, :class => 'btn btn-secondary'

app/views/subjects/index.html.haml
/ This file is app/views/movies/index.html.erb
%h2 All Subjects
  
%table#movies.table.table-striped.col-md-12
  %thead
    %tr
      %th Title
  %tbody
    - @subjects.each do |subject|
      %tr
        %td
          = subject.title
        %td
          = link_to "More about #{subject.title}", subject_path(subject)
        %td
          = link_to 'Show', subject
        %td
          = link_to 'Edit', edit_subject_path(subject)
        %td
          = link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' }

app/views/subjects/new.html.haml
%h2 Create New Subject
= form_tag subjects_path do
  = label :subject, :subjectcode, 'Subject Code', :class => 'col-form-label'
  = text_field :subject, :subjectcode, :class => 'form-control'
  = label :subject, :title, 'Title', :class => 'col-form-label'
  = text_field :subject, :title, :class => 'form-control'
  %br
  = submit_tag 'Save Changes', :class => 'btn btn-primary'
  = link_to 'Cancel', subjects_path, :class => 'btn btn-secondary'

app/views/subjects/show.html.haml
%h3 Details about #{@subject.title}

%ul#details
  %li
    Subject code:
    = @subject.subjectcode
  %li
    Title:
    = @subject.title

%h4 Description:

%p#description= @subject.description

= link_to 'Edit', edit_subject_path(@subject)
= button_to 'Delete', subject_path(@subject), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-primary'
= link_to 'Back to Subject list', subjects_path