config/routes.rb
Rails.application.routes.draw do
 
  resources :pairings
  resources :profiles
  resources :subjects
  resources :schedules
  match '/auth/:provider/callback', :to => 'sessions#create', :via => [:get, :post]
  match 'auth/failure', :to => 'sessions#failure', :via => [:get, :post]
  match 'sessions/destroy', :as => 'logout', :via => [:get, :post]
  get 'sessions/start_test'
  get 'sessions/clear'
  get 'session/debug'

  get 'welcome/landing', :as => :welcome_landing
  get 'about/index'

  resources :users, only: [:destroy] do
    resources :profiles, only: [:show, :edit, :update, :destroy]
  end

  root 'welcome#landing'
  
  get 'schedules/index'

end

app/views/layouts/_flash.html.haml
- if flash[:notice]
  #notice.alert.alert-info{role: "alert"}
    = flash[:notice]
- elsif flash[:warning]
  #warning.alert.alert-danger{role: "alert"}
    = flash[:warning]

app/views/layouts/_footer.html.haml
%div
= button_to "Log Out", logout_path

app/views/layouts/application.html.haml
!!!
%html
  %body
    %title Student-Tutor Pairing
    %link{crossorigin: "anonymous", href: "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css", integrity: "sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z", rel: "stylesheet"}/
    = stylesheet_link_tag 'application', 'media' => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %nav.navbar.navbar-expand-lg.bg-primary.text-white.mb-3
      %h1
      - unless @action == 'login'
        = link_to " Student-Tutor Pairing ", subjects_path
        &nbsp&nbsp&nbsp&nbsp
        = link_to " Add subject ", new_subject_path
        &nbsp&nbsp&nbsp&nbsp
        = link_to " Schedule a Session ", schedules_path
        &nbsp&nbsp&nbsp&nbsp
        = link_to " About us ", about_index_path
      - else
        = link_to "Student-Tutor Pairing", welcome_landing_path 
    .container
      = render 'layouts/flash'
      %main#main
        = yield
        - unless @action == 'login'
          = render "layouts/footer"